export enum PermissionEnum {
    "PermissionScene.Save.Permission" = 2,
    "PermissionScene.Edit.Permission" = 3,
    "PermissionScene.Delete.Permission" = 4,
    "RoleScene.Save.Permission" = 6,
    "RoleScene.Edit.Permission" = 7,
    "RoleScene.Delete.Permission" = 8,
    "OrganizationScene.Save.Permission" = 10,
    "OrganizationScene.Edit.Permission" = 11,
    "OrganizationScene.Delete.Permission" = 12,
    "UserScene.Save.Permission" = 14,
    "UserScene.Edit.Permission" = 15,
    "UserScene.Delete.Permission" = 16,
    "MenuScene.Save.Permission" = 18,
    "MenuScene.Edit.Permission" = 19,
    "MenuScene.Delete.Permission" = 20,
  }